name: zVanish
version: 1.1
main: me.empire.zvanish.zVanish
api-version: 1.18
authors: [ EmpireMTR ]
commands:
  vanish:
    aliases: [v, zvanish, zv]
    description: Allows you to vanish yourself or other players!